source("functions/fun_generic_latin1.r")
source("functions/fun_indicateurs_france_latin1.r")
source("functions/fun_indicateurs_local_latin1.r")
source("functions/fun_rmd_latin1.r")
source("functions/fun_mainSTOCreporting_latin1.r")
